flask_server/models.py
from flask_login import UserMixin


class User(UserMixin):
    pass

flask_server/forms.py
from flask import app, current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from flask_wtf.form import _Auto
from wtforms import StringField, SubmitField, PasswordField
from flask_bootstrap import SwitchField
from wtforms.validators import InputRequired, Length, DataRequired


class LoginForm(FlaskForm):
    username = StringField(validators=[
                           DataRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[
                             DataRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField('Login')

class NewProfileForm(FlaskForm):
    name = StringField(validators=[
                        DataRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Name"})
    
    files = FileField('Image', render_kw={"placeholder": "Upload File", "multiple" : "True", "accept": ".jpg"})

    submit = SubmitField('Add Profile')



class SwitchThemeForm(FlaskForm):
    
    power_switch = SwitchField('Dark Mode', render_kw = {'onchange' : "sendSwitchValue()", 'id' : 'themeSwitch'})

    def check(self, check):
        self.power_switch.render_kw['checked'] = check
        return self

flask_server/api_blueprint.py
from flask import Blueprint, Response, current_app, redirect, render_template, url_for
from flask_login import login_required


api_blueprint = Blueprint('api_blueprint', __name__)

@api_blueprint.before_request
@login_required
def require_login():
    pass


@api_blueprint.route('/video_feed')
def video_feed():
    return Response(current_app.pi_guardian.generate_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')

flask_server/auth_blueprint.py
from flask import Blueprint, current_app, redirect, render_template, url_for
from flask_login import current_user, login_required, login_user, logout_user

from flask_server.forms import LoginForm
from flask_server.models import User


auth_blueprint = Blueprint('auth_blueprint', __name__)


@auth_blueprint.route('/', methods=['GET', 'POST'])
def auth():
    login_form: LoginForm = LoginForm()

    if login_form.validate_on_submit():
        username, password = login_form.username.data, login_form.password.data
        if not current_app.authenticate_user(username, password):
            return
        user = User()
        user.id = username
        login_user(user)
        return redirect(url_for('views_blueprint.home'))
    
    if current_user.is_authenticated:
        return redirect(url_for('views_blueprint.home'))

    return render_template('auth.html', login_form=login_form)

@auth_blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.auth'))

flask_server/blueprints/api.py
from flask import Blueprint, Response, current_app, redirect, render_template, request, url_for
from flask_login import login_required


api_blueprint = Blueprint('api_blueprint', __name__, static_url_path='profiles/photos' ,static_folder='../../dataset/')

@api_blueprint.before_request
@login_required
def require_login():
    pass


@api_blueprint.route('/video_feed')
def video_feed():
    return Response(current_app.pi_guardian.generate_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')

@api_blueprint.route('/pic')
def take_picture():
    current_app.pi_guardian.take_picture()
    return redirect(url_for('views_blueprint.home'))

@api_blueprint.route('/change_theme', methods=['POST'])
def change_theme():
    dark_mode = 'True' if request.form.get('switchValue') == 'true' else ''
    current_app.config['BOOTSTRAP_BOOTSWATCH_THEME'] = 'darkly' if dark_mode else 'lumen'
    current_app.update_flask_config('dark_mode' , dark_mode)
    return 'sucess'

flask_server/blueprints/auth.py
from flask import Blueprint, current_app, redirect, render_template, url_for
from flask_login import current_user, login_required, login_user, logout_user

from flask_server.forms import LoginForm
from flask_server.models import User


auth_blueprint = Blueprint('auth_blueprint', __name__)


@auth_blueprint.route('/', methods=['GET', 'POST'])
def auth():
    login_form: LoginForm = LoginForm()

    if login_form.validate_on_submit():
        username, password = login_form.username.data, login_form.password.data
        if not current_app.authenticate_user(username, password):
            return
        user = User()
        user.id = username
        login_user(user)
        return redirect(url_for('views_blueprint.home'))
    
    if current_user.is_authenticated:
        return redirect(url_for('views_blueprint.home'))

    return render_template('auth.html', login_form=login_form)

@auth_blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.auth'))

flask_server/blueprints/views.py
import os
import re
from time import sleep
import unicodedata
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import login_required
from werkzeug.utils import secure_filename


from flask_server.forms import NewProfileForm

views_blueprint = Blueprint('views_blueprint', __name__)

@views_blueprint.before_request
@login_required
def require_login():
    pass

@views_blueprint.route('/')
def home():
    return render_template('home.html')

@views_blueprint.route('/profiles', methods=['GET', 'POST'])
def profiles():

    profiles = current_app.get_profiles()

    new_profile_form: NewProfileForm = NewProfileForm()

    if new_profile_form.validate_on_submit():

        files = []

        for file_obj in list(request.files.listvalues())[0]:

            filename = secure_filename(file_obj.filename)
            # Access file data
            file_data = file_obj.read()  # Read file content

            files.append([filename, file_data])

        folder_name = new_profile_form.name.data

        current_app.add_profile(folder_name, files)

        # flash('Profile Created')
        sleep(3)
        return render_template('profiles.html', profiles=profiles, new_profile_form=new_profile_form)


    return render_template('profiles.html', profiles=profiles, new_profile_form=new_profile_form)

flask_server/views_blueprint.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_required

views_blueprint = Blueprint('views_blueprint', __name__)

@views_blueprint.before_request
@login_required
def require_login():
    pass

@views_blueprint.route('/')
def home():
    return render_template('home.html')

flask_server/templates/auth.html
{% from 'bootstrap5/form.html' import render_form %}
{% extends 'base.html' %}

{% block sidebar %}{% endblock %}

{% block content %}
<div class="pt-5">
    <div class="container card p-5 mt-5 rounded-4 w-75">
        <h1>Welcome</h1>
        <h4>Please login</h4>
        
        <hr>
        
        {{ render_form(login_form) }}
    </div>
</div>
{% endblock %}

flask_server/templates/base.html
{% from 'bootstrap5/form.html' import render_form %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> PiGuardian </title>
    <!-- Bootstrap CSS -->
    {{ bootstrap.load_css() }}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <script defer src="https://kit.fontawesome.com/57c78119e7.js" crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <script defer src="{{ url_for('static', filename='script.js') }}"></script>
</head>

<body>

    <div class="d-flex" style="min-height: 100vh;">

        {% block sidebar %}
        <nav class="d-flex flex-column flex-shrink-0 p-4 text-white bg-dark container" style="width: 15%;">
            <a href="{{ url_for('views_blueprint.home') }}" class="text-white text-decoration-none">
                <h3>
                    <i class="fa fa-user-secret" aria-hidden="true"></i>
                    PiGuardian
                </h3>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                
                <li class="nav-item">
                    <a href="{{ url_for('views_blueprint.home') }}" class="nav-link" aria-current="page"><i class="fa fa-home"></i> Home</a>
                </li>

                <li class="nav-item">
                    <a href="{{ url_for('views_blueprint.profiles') }}" class="nav-link" aria-current="page"><i class="fa fa-users"></i> Profiles</a>
                </li>
                
            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                    <strong>mdo</strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    <li>
                        {{render_form(get_theme_switch_form())}}
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{ url_for('auth_blueprint.logout') }}">Sign out</a></li>
                </ul>
            </div>
        </nav>
        {% endblock %}

        
        <main class="flex-column container p-5">
            <!-- Page Content -->
            <div class="container mt-4">
                {% block content %}
                {% endblock %}
            </div>
        </main>

    </div>

    <!-- Bootstrap JS -->
    {{ bootstrap.load_js() }}

    <script>
        function sendSwitchValue() {
          var switchElement = document.getElementById('themeSwitch');
          var switchValue = switchElement.checked;
    
          var xhr = new XMLHttpRequest();
          xhr.open('POST', '/api/change_theme', true);
          xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
          xhr.onreadystatechange = function() {
            if (xhr.readyState === 4 && xhr.status === 200) {
              console.log('Switch value sent successfully');
              location.reload(); // Refresh the page
            }
          };
          xhr.send('switchValue=' + switchValue);
        }
      </script>

</body>

</html>

flask_server/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>Welcome to PiGuardian!</h1>

        <h3>Your ultimate Raspberry Pi security system.</h3>
        
        <p>
            Secure your space with the power of PiGuardian, your trusted companion in safeguarding what matters most. Whether it's your home, office, or any other personal space, PiGuardian combines cutting-edge technology with ease of use to provide you with complete peace of mind.
        </p>
    </div>
</div>

<hr>

<div>

    <div class="container">

        <div class="row text-center">

            <div class="col w-50">
                <a data-bs-toggle="modal" data-bs-target="#videoModal">
                    <img class="camera-bg img-fluid" class="center" src="{{ url_for('api_blueprint.video_feed') }}">
                </a>
            </div>

        </div>
    </div>

</div>


<div class="modal fade" id="videoModal" tabindex="-1" aria-labelledby="videoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="videoModalLabel">New message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body align-self-center w-75">
                <img class="camera-bg img-fluid w-100" class="center" src="{{ url_for('api_blueprint.video_feed') }}">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

flask_server/templates/profiles.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="row">
    <div>
        <h1>Your Profiles</h1>

        <p>These are your users safely registered with us.</p>

        <button class="btn btn-primary new-button float-end" data-bs-toggle="modal" data-bs-target="#newProfileModal">
            New Profile <i class="fa fa-plus p-1" aria-hidden="true"></i>
        </button>
    </div>
</div>

<hr>

<div>

    <div class="container">

        <div id="main-content" class="file_manager">
            <div class="container">
                <div class="row clearfix">


                    {% for profile in profiles %}

                    <div class="col-lg-3 col-md-4 col-sm-12 p-3">
                        <div class="card">
                            <div class="file position-relative">
                                <div class="overflow-hidden" style="height: 200px;">
                                    <img src="{{ url_for('api_blueprint.static', filename=profile[1]) }}"
                                        class="img-fluid" width="260px" height="195px">
                                </div>
                                <div class="file-name p-2 pt-3 text-center">
                                    <h4 class="m-b-5 text-muted text-capitalize">{{ profile[0] }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}



                </div>

            </div>
        </div>
    </div>

</div>

<div class="modal fade" id="newProfileModal" tabindex="-1" aria-labelledby="newProfileModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="videoModalLabel">New Profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="row p-3 modal-body">
                
                <div class="col w-50">
                    {{ render_form(new_profile_form, render_kw={'enctype' : 'multipart/form-data'}) }}
                </div>
                
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Add new profile</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}